server:
  port: 8081

spring:
  application:
    name: url-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DATABASE:urlshortener}}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
      retries: 3
  cloud:
    vault:
      enabled: ${VAULT_ENABLED:false}
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
      scheme: http
      authentication: TOKEN
      token: ${VAULT_TOKEN:root}
      kv:
        enabled: true
        backend: secret
        default-context: url-service

url-service:
  base-url: ${BASE_URL:http://localhost:8080}

kafka:
  topics:
    click-events: url.click.events
